name: Build, Test and Deploy rangurura App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0

      - name: Build Docker Image
        run: docker build -t rangurura .

      - name: Tag Docker Image
        run: docker tag rangurura:latest docker.io/valens200/rangurura:latest

      - name: Docker Login and Push
        run: |
          echo "Kiwikwingi2003" | docker login -u valens200 --password-stdin docker.io
          docker push docker.io/valens200/rangurura:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create .ssh Directory
        run: mkdir -p $HOME/.ssh

      - name: Create known_hosts File
        run: touch $HOME/.ssh/known_hosts

      - name: Remove Old Host Key
        run: ssh-keygen -R 194.163.167.131

      - name: Add and Display Updated Host Key
        run: |
          HOST_KEY=$(ssh-keyscan -t rsa 194.163.167.131)
          echo "$HOST_KEY"
          echo "$HOST_KEY" >> $HOME/.ssh/known_hosts

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 194.163.167.131
          port: 22
          username: root
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          password: bxnnHBAuNECS3a6m
          fingerprint: ${{ secrets.DEPLOY_FINGERPRINT }}
          script: |
            echo "Kiwikwingi2003" | docker login -u "valens200" --password-stdin docker.io
            sudo docker pull docker.io/valens200/rangurura
            sudo docker stop rangurura || true
            sudo docker rm rangurura || true
            sudo docker run -d --name rangurura -p 7300:5000 docker.io/valens200/rangurura
